package life.lyp.community.community.model;

import lombok.Data;

@Data
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.id
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.account_id
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.name
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.token
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.gmt_create
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.gmt_modified
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.bio
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    private String bio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.avatar_url
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    private String avatarUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.id
     *
     * @return the value of user_table.id
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.id
     *
     * @param id the value for user_table.id
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.account_id
     *
     * @return the value of user_table.account_id
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.account_id
     *
     * @param accountId the value for user_table.account_id
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.name
     *
     * @return the value of user_table.name
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.name
     *
     * @param name the value for user_table.name
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.token
     *
     * @return the value of user_table.token
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.token
     *
     * @param token the value for user_table.token
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.gmt_create
     *
     * @return the value of user_table.gmt_create
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.gmt_create
     *
     * @param gmtCreate the value for user_table.gmt_create
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.gmt_modified
     *
     * @return the value of user_table.gmt_modified
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.gmt_modified
     *
     * @param gmtModified the value for user_table.gmt_modified
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.bio
     *
     * @return the value of user_table.bio
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.bio
     *
     * @param bio the value for user_table.bio
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    public void setBio(String bio) {
        this.bio = bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.avatar_url
     *
     * @return the value of user_table.avatar_url
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.avatar_url
     *
     * @param avatarUrl the value for user_table.avatar_url
     *
     * @mbg.generated Sat Mar 14 21:23:18 CST 2026
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }
}