server.port=8887

github.client.id=Ov23liu7u0LxU3empmnb
github.client.secret=44cce246bce0e57d9f40e0514ce66019671c9294
github.redirect.uri=http://localhost:8887/callback

proxy.enabled=true
proxy.host=127.0.0.1
proxy.port=7890

spring.datasource.url=jdbc:mysql://localhost:3306/community
spring.datasource.username=root
spring.datasource.password=032581
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
logging.level.life.lyp.community.community.mapper = debug